import 'package:quran/features/quran/domain/usecases/get_resicuter_usecase.dart';
import 'package:quran/features/quran/states/quran_by_reciter/quran_by_reciter_bloc.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:injectable/injectable.dart';
import 'package:quran/cores/usecase/usecase.dart';

part 'reciter_event.dart';
part 'reciter_state.dart';

part 'reciter_bloc.freezed.dart';

@lazySingleton
class ReciterBloc extends Bloc<ReciterEvent, ReciterState> {
  final QuranByReciterBloc _songsByArtistBloc;
  final GetRecicterUsecase _getRecicterUsecase;

  final List<String> suarsArabicName = [
    'الفاتحة',
    'البقرة',
    'آل عمران',
    'النساء',
    'المائدة',
    'الأنعام',
    'الأعراف',
    'الأنفال',
    'التوبة',
    'يونس',
    'هود',
    'يوسف',
    'الرعد',
    'ابراهيم',
    'الحجر',
    'النحل',
    'الإسراء',
    'الكهف',
    'مريم',
    'طه',
    'الأنبياء',
    'الحج',
    'المؤمنون',
    'النور',
    'الفرقان',
    'الشعراء',
    'النمل',
    'القصص',
    'العنكبوت',
    'الروم',
    'لقمان',
    'السجدة',
    'الأحزاب',
    'سبإ',
    'فاطر',
    'يس',
    'الصافات',
    'ص',
    'الزمر',
    'غافر',
    'فصلت',
    'الشورى',
    'الزخرف',
    'الدخان',
    'الجاثية',
    'الأحقاف',
    'محمد',
    'الفتح',
    'الحجرات',
    'ق',
    'الذاريات',
    'الطور',
    'النجم',
    'القمر',
    'الرحمن',
    'الواقعة',
    'الحديد',
    'المجادلة',
    'الحشر',
    'الممتحنة',
    'الصف',
    'الجمعة',
    'المنافقون',
    'التغابن',
    'الطلاق',
    'التحريم',
    'الملك',
    'القلم',
    'الحاقة',
    'المعارج',
    'نوح',
    'الجن',
    'المزمل',
    'المدثر',
    'القيامة',
    'الإنسان',
    'المرسلات',
    'النبإ',
    'النازعات',
    'عبس',
    'التكوير',
    'الإنفطار',
    'المطففين',
    'الإنشقاق',
    'البروج',
    'الطارق',
    'الأعلى',
    'الغاشية',
    'الفجر',
    'البلد',
    'الشمس',
    'الليل',
    'الضحى',
    'الشرح',
    'التين',
    'العلق',
    'القدر',
    'البينة',
    'الزلزلة',
    'العاديات',
    'القارعة',
    'التكاثر',
    'العصر',
    'الهمزة',
    'الفيل',
    'قريش',
    'الماعون',
    'الكوثر',
    'الكافرون',
    'النصر',
    'المسد',
    'الإخلاص',
    'الفلق',
    'الناس'
  ];

  final List<String> suarsTranslatedName = [
    'The Opener',
    'The Cow',
    'Family of Imran',
    'The Women',
    'The Table Spread',
    'The Cattle',
    'The Heights',
    'The Spoils of War',
    'The Repentance',
    'Jonah',
    'Hud',
    'Joseph',
    'The Thunder',
    'Abraham',
    'The Rocky Tract',
    'The Bee',
    'The Night Journey',
    'The Cave',
    'Mary',
    'Ta-Ha',
    'The Prophets',
    'The Pilgrimage',
    'The Believers',
    'The Light',
    'The Criterion',
    'The Poets',
    'The Ant',
    'The Stories',
    'The Spider',
    'The Romans',
    'Luqman',
    'The Prostration',
    'The Combined Forces',
    'Sheba',
    'Originator',
    'Ya Sin',
    'Those who set the Ranks',
    'The Letter "Saad"',
    'The Troops',
    'The Forgiver',
    'Explained in Detail',
    'The Consultation',
    'The Ornaments of Gold',
    'The Smoke',
    'The Crouching',
    'The Wind-Curved Sandhills',
    'Muhammad',
    'The Victory',
    'The Rooms',
    'The Letter "Qaf"',
    'The Winnowing Winds',
    'The Mount',
    'The Star',
    'The Moon',
    'The Beneficent',
    'The Inevitable',
    'The Iron',
    'The Pleading Woman',
    'The Exile',
    'She that is to be examined',
    'The Ranks',
    'The Congregation, Friday',
    'The Hypocrites',
    'The Mutual Disillusion',
    'The Divorce',
    'The Prohibition',
    'The Sovereignty',
    'The Pen',
    'The Reality',
    'The Ascending Stairways',
    'Noah',
    'The Jinn',
    'The Enshrouded One',
    'The Cloaked One',
    'The Resurrection',
    'Man',
    'The Emissaries',
    'The Tidings',
    'Those who drag forth',
    'He Frowned',
    'The Overthrowing',
    'The Cleaving',
    'The Defrauding',
    'The Sundering',
    'The Mansions of the Stars',
    'The Nightcommer',
    'The Most High',
    'The Overwhelming',
    'The Dawn',
    'The City',
    'The Sun',
    'The Night',
    'The Morning Hours',
    'The Relief',
    'The Fig',
    'The Clot',
    'The Power',
    'The Clear Proof',
    'The Earthquake',
    'The Courser',
    'The Calamity',
    'The Rivalry in world increase',
    'The Declining Day',
    'The Traducer',
    'The Elephant',
    'Quraysh',
    'The Small kindnesses',
    'The Abundance',
    'The Disbelievers',
    'The Divine Support',
    'The Palm Fiber',
    'The Sincerity',
    'The Daybreak',
    'Mankind'
  ];

  final List<String> suarsEnglishName = [
    "Al-Fatihah",
    "Al-Baqarah",
    "Ali Imran",
    "An-Nisa",
    "Al-Ma'idah",
    "Al-An'am",
    "Al-A'raf",
    "Al-Anfal",
    "At-Tawbah",
    "Yunus",
    "Hud",
    "Yusuf",
    "Ar-Raad",
    "Ibrahim",
    "Al-Hijr",
    "An-Nahl",
    "Al-Isra",
    "Al-Kahf",
    "Maryam",
    "Taha",
    "Al-Anbya",
    "Al-Hajj",
    "Al-Muminun",
    "An-Nur",
    "Al-Furqan",
    "Ash-Shuara",
    "An-Naml",
    "Al-Qasas",
    "Al-Ankabut",
    "Ar-Rum",
    "Luqman",
    "As-Sajdah",
    "Al-Ahzab",
    "Saba",
    "Fatir",
    "Ya-Sin",
    "As-Saffat",
    "Sad",
    "Az-Zumar",
    "Ghafir",
    "Fussilat",
    "Ash-Shuraa",
    "Az-Zukhruf",
    "Ad-Dukhan",
    "Al-Jathiyah",
    "Al-Ahqaf",
    "Muhammad",
    "Al-Fath",
    "Al-Hujurat",
    "Qaf",
    "Adh-Dhariyat",
    "At-Tur",
    "An-Najm",
    "Al-Qamar",
    "Ar-Rahman",
    "Al-Waqi'ah",
    "Al-Hadid",
    "Al-Mujadila",
    "Al-Hashr",
    "Al-Mumtahanah",
    "As-Saf",
    "Al-Jumu'ah",
    "Al-Munafiqun",
    "At-Taghabun",
    "At-Talaq",
    "At-Tahrim",
    "Al-Mulk",
    "Al-Qalam",
    "Al-Haqqah",
    "Al-Ma'arij",
    "Nuh",
    "Al-Jinn",
    "Al-Muzzammil",
    "Al-Muddaththir",
    "Al-Qiyamah",
    "Al-Insan",
    "Al-Mursalat",
    "An-Naba",
    "An-Nazi'at",
    "Abasa",
    "At-Takwir",
    "Al-Infitar",
    "Al-Mutaffifin",
    "Al-Inshiqaq",
    "Al-Buruj",
    "At-Tariq",
    "Al-A'la",
    "Al-Ghashiyah",
    "Al-Fajr",
    "Al-Balad",
    "Ash-Shams",
    "Al-Layl",
    "Ad-Duhaa",
    "Ash-Sharh",
    "At-Tin",
    "Al-Alaq",
    "Al-Qadr",
    "Al-Bayyinah",
    "Az-Zalzalah",
    "Al-Adiyat",
    "Al-Qari'ah",
    "At-Takathur",
    "Al-Asr",
    "Al-Humazah",
    "Al-Fil",
    "Quraysh",
    "Al-Ma'un",
    "Al-Kawthar",
    "Al-Kafirun",
    "An-Nasr",
    "Al-Masad",
    "Al-Ikhlas",
    "Al-Falaq",
    "An-Nas"
  ];

  @override
  onChange(Change<ReciterState> change) {
    super.onChange(change);
    loadSongsByArtists(change.nextState.artists ?? []);
  }

  void loadSongsByArtists(List<String> artists) {
    if (artists.isEmpty) {
      return;
    }
    for (var i = 0; i < artists.length; i++) {
      if (artists[i].isEmpty) {
        continue;
      }
      _songsByArtistBloc.add(QuranByReciter.loadQuran(artists[i]));
    }
  }

  ReciterBloc(
      {@preResolve required GetRecicterUsecase getRecicterUsecase,
      @preResolve required QuranByReciterBloc songsByArtistBloc})
      : _getRecicterUsecase = getRecicterUsecase,
        _songsByArtistBloc = songsByArtistBloc,
        super(ReciterState.loading()) {
    on<ReciterEvent>((event, emit) {
      return event.maybeMap<void>(
        loadPopularArtist: (value) async {
          await _loadPopularArtistEventCallback(emit: emit);
          return;
        },
        orElse: () {
          return;
        },
      );
    });
  }
  Future<void> _loadPopularArtistEventCallback(
      {required Emitter<ReciterState> emit}) async {
    emit(ReciterState.loading(artists: state.artists ?? []));
    var result = await _getRecicterUsecase(NoUsecaseParams());
    return result.map<void>(ok: (ok) {
      emit(ReciterState.loaded(artists: ok.data));
      return;
    }, err: (err) {
      emit(ReciterState.error(
          error: err.data.message, artists: state.artists ?? []));
      return;
    });
  }
}
